apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
  selfLink: /api/v1/namespaces/default/services/mysql
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    io.kompose.service: mysql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
