apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: sample-webservice-nginx
  name: sample-webservice-nginx
  selfLink: /api/v1/namespaces/default/services/sample-webservice-nginx
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    io.kompose.service: sample-webservice-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
