apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webservice
  name: webservice
  selfLink: /api/v1/namespaces/default/services/webservice
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    io.kompose.service: webservice
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
