apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    io.kompose.service: webservice
  name: webservice
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/webservice
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      io.kompose.service: webservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webservice
    spec:
      containers:
      - args:
        - server
        env:
        - name: DB
          value: mysql
        - name: DB_ADDRESS
          value: mysql:3306
        - name: REDIS_ADDRESS
          value: redis:6379
        image: ravjotsingh/sample-webservice
        imagePullPolicy: Always
        name: webservice
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
